version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-financial-planner
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: financial-planner-db
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-financial-planner
    ports:
      - '6379:6379'

  app:
    build: .
    container_name: nestjs-app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    networks:
      - nestjs
networks:
  nestjs:
volumes:
  postgres_data:
